### ISSUE TITLE
Different Coffers

### ISSUE THREAD

**Issue by gomsnothereman** [BigRedBrent/NeverwinterInvokeBot#11]
If i wanted the script to use(buy) a different coffer it would be the coffer.png i believe?? (looking at the code), however i also see an artifactequipmentcoffer.png, on one account i do buy the things to upgrade artifact(s) but on another i just buy the crafter bags though i am going to change that to the bag to upgrade runes eventually (because runes those are tradeable).. just wanted to know which png to replace to modify the item purchased.

Aso it might speed things up to do a "check" still on the grey vs white Ctrl-i in the upper right of the GUI, reason being is if the character is not even IN the "invoke" area that turns grey, and i keep 1 character out of the area recently because of his MASSIVE xp bonus from the old invoking system..

GREAT work on this new system/method though, you really seem to have made it near on effortless and idiot proof :) love how you are grabbing and manually resizing the window so everyone is the same then, great idea!

**Comment by BigRedBrent** [comment]
In the Settings.au3 file you can change the $Coffer option to have it select a different coffer.

The image detection was getting a false positive with the grayed out invoke, so I set it back to useing pixel detection. The $GrayedOutInvokeX $GrayedOutInvokeY $GrayedOutInvokeC options need to be configured for the right color for that to work.

**Comment by dexterlazy** [comment]
So I change the image for ArtifactEquipment to a new image of Elixir of Fate but it does not seem to detect it. What do I need to do to make it select the Elixir of Fate instead?

**Comment by BigRedBrent** [comment]
I renamed the image files removing the word Coffer, and I added images for the other items.
