### ISSUE TITLE
Spam blocker

### ISSUE THREAD

**Issue by Lunarcy12** [BigRedBrent/NeverwinterInvokeBot#13]
Is it possible for someone to add something to block spammers?  Use parameters like <>, .c0m, etc and just automatically block them, maybe during the evoke process?  I have 30 chars, so there is a lot of time spent in game and by the end, a lot of spammers could be blocked.  Im not sure how or even if that would work because of the clicking but I thought I'd ask because it is such a pervasive issue after inspection.

**Comment by BigRedBrent** [comment]
Not sure. This script certainly has nothing remotely close to that ability.

**Comment by dexterlazy** [comment]
The best way to do this is use the command 
/hide
this will hide you from everyone but guild members. One of the first things I do.
Also this command will stop party invites
/lft

**Comment by Lunarcy12** [comment]
Oh they dont PM me, I have used bots on other games that could do this.  They might have had the bnlock list client side though now that I think about it.
