### ISSUE TITLE
Windows 10 - Window not found

### ISSUE THREAD

**Issue by dexterlazy** [BigRedBrent/NeverwinterInvokeBot#27]
Windows 10 - Window not found
It starts up the client and even re-sizes it
any ideas?

**Comment by BigRedBrent** [comment]
I have not tested it on windows 10. Perhaps it is not compatible.

**Comment by shonsu02** [comment]
It works on Windows 10.  I have it running on one.

**Comment by dexterlazy** [comment]
shonsu02 did you do anything differently? or just download and run?

I can see the GameClient.exe in task manager. But the script is not detecting it.

**Comment by shonsu02** [comment]
It was a computer that was upgraded from Win 7 that was already running it.  I didn't have to do anything at all.  It just ran after upgrading.

**Comment by Love42se** [comment]
I did some debugging and the call to get a PID from GameClient.exe returns a bogus PID. I switched the code to use window title and that works for me.
In shared.au3 under dependencies, locate the function FindWindow()

Replace the line
    Local $PID = ProcessExists("GameClient.exe")

with 
    Local $PID = WinGetProcess("Neverwinter")

I've never done anything in autoit so this is just a hack to get around the problem

**Comment by Love42se** [comment]
Oh, and I also run Windows 10 upgraded from Windows 7

**Comment by Love42se** [comment]
No, it is stilled called GameClient.exe

**Comment by dexterlazy** [comment]
Tried all that you advised but still did not work.

I did find out that for some stupid reason if I have Teamviewer running it will stop the script working.
Closed Teamviewer by mistake one day and the script just started to work!!!!
Must be something to do with Windows 10 and Teamviewer as I have another PC with Windows 7 and Teamviewer running all the time and it is fine.

**Comment by SummerBear12** [comment]
I used to have no issues on windows 10 and having team viewer open 
I found after a re-install that I'm now having the same issue. The moment I close the team-viewer client on the desktop the script works perfectly.
