### ISSUE TITLE
modifying invoke attempt tries and Method

### ISSUE THREAD

**Issue by gomfedj** [BigRedBrent/NeverwinterInvokeBot#6]
I see you put in a limit on the number of times it will try to invoke before logging out, is that this section of code?

For $j = 1 to 40
            FindLogInScreen()
            Send($InvokeKey)
            Sleep(500)

does that mean it tries 40 times to invoke?? reason i ask is i noticed the past week or so i have not gotten all 6 invokes completed at times (totally randomly some character get 6 some don't.. i am sure it is just because of the massive lag running it on a VM)

I may not need to change that but just wanted to check to be sure that was the right area.. I made some changes yesterday that SEEM to of helped get the invokes to "complete" not sure if it will skip any (will take a few days of running it to make sure) I changed your ^i to this..

$InvokeKey = "{CTRLDOWN}i{CTRLUP}"

also increased to 200 this option
AutoItSetOption("SendKeyDownDelay", 200)

It looks like 1st try it is getting it 90% of the time (instead of inventory opening/closing several times because it is picking up the I not the Ctrl..)

Also finally, what is the reason you put in the 40 attempt on invoke? is to because of the weirdness with the vault of piety window? (i have NOT had it hang up there again to my knowledge, no idea WHY the window is sometimes just a TINY BIT different it isn't with any perticular diety/character/area it is just... random!) If it is because of being outside the invoke area, the script should pick that up because of the greyed out ctrl-i

**Comment by BigRedBrent** [comment]
It used to just try until it would time out. I added a limit of 40 tries because that would take 20 seconds, and if it doesn't do it in 20 seconds, then it probably will not do it, so I want it to skip.

**Comment by gomfedj** [comment]
hmmmmm!!!!! i wonder if THAT is why i would sometimes come back to the system and have a login screen with a "timeout" message for the script... i have not seen that recently, but shocked it would try it so long the script timed out (it is like a 20 minute timer isn't it!)...

**Comment by BigRedBrent** [comment]
I have implemented a few of your changes. I allowed the key delay to be customizable in the Settings.au3 file.
