### ISSUE TITLE
New Invoke Issues

### ISSUE THREAD

**Issue by Lunarcy12** [BigRedBrent/NeverwinterInvokeBot#8]
On the first invoke, it doesnt usually work correctly.  It sometimes takes a few tries.  I notice with the script that I have been having to manually do the first round (Difficult because I have a LOT of chars) and then the last 5 can be done by script with only a few missed.  

Anyone else getting these issues?  I hate to give up on prayer cause I need those coals but doing it manually takes an hour.  lol

**Comment by BigRedBrent** [comment]
Have you tried the latest version? I was having an issue as well. I changed it to retry invoking every 5 seconds instead of every half a second and it seemed to work for me.

**Comment by NumberB** [comment]
Lunarcy is correct, the very first invoke is odd. I'll try to explain:

Log in, ctrl+I (invoke) - the animation goes and is successful, but the daily celestial coins does not increment nor does the first 15 min timer start. Instead, if you wait for ~4.5 seconds the screen itself actually goes into "alt" mode (dim with cursor available). Once you are at this point you can invoke again for your first true invoke and everything goes as normal.

It is really strange. It's almost as if the first invoke goes through it's own server script and see's "oh, things have reset, let me clean it up for you" and goes and cleans things up but then leaves you fresh with no invokes.

Also after the real invoke if you "esc" out from the "rewards" menu that tells you what you just got from invoking it will just come up yet again after the invoking animation completes.

I thought it might have been a "first invoke after patch" problem but all of my toons have exhibited this behavior after several days so it is persistent.

I think doing a first invoke, pausing completely for 4.5 seconds, then doing a second invoke will fix this.

**Comment by BigRedBrent** [comment]
The 2.16 script does invoke first, waits 5 seconds before trying to invoke, then invokes again. It is working fine for me this way so far.

**Comment by NumberB** [comment]
I should add I run without all the pixel colors setup so the script knows where it is at by looking at the screen. I haven't taken the time to set that up since I run NW in windowed mode and don't want to take the time to set all that up in case the window moves at some point (it happens). I'm guessing you have all this setup? Because for me my characters log in, try to invoke once, then log out.

**Comment by BigRedBrent** [comment]
I could set that to wait 5 seconds, but that would take 20 seconds just to invoke for each character.

**Comment by Lunarcy12** [comment]
Can you add that as a manual setting?  I tired setting up all the pixels but no matter where I put the coordinates, it will not recognise being in game.  It does login, but not game.  I switched the pixels at least 20 times before I gave up and went back to the old method.

**Comment by BigRedBrent** [comment]
I like to use the left border of your characters level indicator at the top left of the screen for in game detection. But at the very least you need to set up detection for the GrayedOutInvokeButton. I use the grayed out Ctrl+I icon at the top right of the screen just below the invoke icon.

**Comment by gomfedj** [comment]
pixels work GREAT for me.. i run it at 800X600.. and i used like the right hand edge of the radar in the upper right area.. just be careful not to select too far in or it might get covered by a destination marker...

without using the pixels i don't think it would work very well anymore... and the way brent has it setup now even if the window moves around, it can still detect the pixels as long as you are at the same resolution..

also to take screen shots use alt-prntscr you want the window with the border/titlebar/etc.. (took me a few tests to figure out that out..)

**Comment by BigRedBrent** [comment]
The latest version uses image searching for most detection, and pixel detection is now relative to the game client window without the border and titlebar. I added a image capture script to copy the game client image to the clipboard.
