### ISSUE TITLE
Settings/color tutorial?

### ISSUE THREAD

**Issue by NumberB** [BigRedBrent/NeverwinterInvokeBot#9]
Is there something somewhere that explains the screen detection settings? I think I might understand it but have put off messing with it because it's just there with no directions.

A quick primer with some screenshots with arrows or whatever would be enough. I'd even do it if I knew how it worked lol.

**Comment by BigRedBrent** [comment]
Yeah, a lot of people have been asking for this. I should really do a video tutorial. I am not sure when I will get around to it though.

**Comment by NumberB** [comment]
Yeah, I get that. Time is always a factor.

For now, can you or someone else help me understand parts of the settings?

```AutoIT
Global $SelectionScreenX = Array("0,      0,      0") ;The X coordinate for the pixel.
Global $SelectionScreenY = Array("0,      0,      0") ;The Y coordinate for the pixel.
Global $SelectionScreenC = Array("FFFFFF, FFFFFF, FFFFFF") ;The Hexadecimal color for the pixel. - http://www.psyclops.com/tools/rgb/
```
How is the Array setup? Is that 3 different pixel points? Does it matter where they are? And do they align top to bottom, like this?:
```AutoIT
Global $SelectionScreenX = Array("Ax,      Bx,      Cx") ;
Global $SelectionScreenY = Array("Ay,      By,      Cy") ;
Global $SelectionScreenC = Array("AAAAAA, BBBBBB, CCCCCC") 
```
There's a bunch of places these are at.

Side question: the login name/password fields... does AutoIT have any way to read hashes? I figure it would be safer to has at least the password (but login wouldn't be bad too) so we could store user/pass in settings but not have it in plain test. Just my paranoia :)

**Comment by BigRedBrent** [comment]
Yes, the arrays do align top to bottom. You can also add as many or as few of them as you like. White spaces are ignored, so you can add as many spaces as you want also.

This would also work:
...
Global $SelectionScreenX = Array("Ax,     Bx") ;
Global $SelectionScreenY = Array("Ay,     By") ;
Global $SelectionScreenC = Array("AAAAAA, BBBBBB") 
...

**Comment by BigRedBrent** [comment]
I added an option to leave the username or password options blank. If they are left blank, the script will prompt you to enter them each time you run the script.

**Comment by dexterlazy** [comment]
Brent are you able to do a short tutorial on how to use the settings file?
I have got the invoking working but it's not loading the settings so cannot get the auto login to work.
So I come back to it and it's logged out and does not re-input login and password.

**Comment by BigRedBrent** [comment]
I added the ability to include a hash of your password. This will only be used to double check that you entered your password in correctly when you run the script.

**Comment by BigRedBrent** [comment]
I removed a lot of the pixel detection with image searching. I left in a few though, because it is a lot faster and the image search did not work well for some of the detection.

The things that are still working with pixel detection are only necessary to increase the speed. Such as detecting when you have scrolled to the top or bottom character, or detecting if you have already invoked on a character (so that it does not have to keep trying to invoke until it reaches max tries and then moves on).

Since there are not nearly as many pixel detection options as there used to be, it should be easier for me to make a tutorial for it, if I ever do decide to make one.
